In [113]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

<IPython.core.display.Javascript object>

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Slicing arrays
"""[start:end]
[start:end:step]"""

In [114]:
a[0]                           ############ Indexing

array([1, 2, 3, 4, 5])

In [115]:
a[1]

array([ 6,  7,  8,  9, 10])

In [116]:
a[1,:3]

array([6, 7, 8])

In [117]:
a[0,2]

3

In [118]:
a[0,1:4]=[4,5,6]
a

array([[ 1,  4,  5,  6,  5],
       [ 6,  7,  8,  9, 10]])

## Dimension 

In [153]:
#### 0-D Arrays
A = np.array(42)
print(A)
print(A.ndim)


#### 1-D Arrays
B = np.array([1, 2, 3, 4, 5])
print(B)
print(B.ndim)


#### 2-D arrays
C = np.array([[1, 2, 3], [4, 5, 6]])
print(C)
print(C.ndim)


#### 3-D arrays
D = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(D)
print(D.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


# Types

In [98]:
np.zeros((3,3))

<IPython.core.display.Javascript object>

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
np.zeros((2,2))

<IPython.core.display.Javascript object>

array([[0., 0.],
       [0., 0.]])

In [100]:
np.ones((4,5))

<IPython.core.display.Javascript object>

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
a=np.full((2,3), 100)
a

<IPython.core.display.Javascript object>

array([[100, 100, 100],
       [100, 100, 100]])

In [104]:
a*5

array([[500, 500, 500],
       [500, 500, 500]])

In [105]:
np.identity(2)

<IPython.core.display.Javascript object>

array([[1., 0.],
       [0., 1.]])

In [139]:
a=np.identity(4)
a

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [140]:
a[2][2]=100

In [141]:
a

array([[  1.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   1.]])

# Random

In [123]:
np.random.rand(2,3)

<IPython.core.display.Javascript object>

array([[0.06445366, 0.97492427, 0.27117548],
       [0.20443356, 0.6278385 , 0.4290725 ]])

In [124]:
np.random.rand(2,3)*100

<IPython.core.display.Javascript object>

array([[62.50499353, 63.02647415,  9.03474097],
       [86.7118891 ,  9.95131535, 45.49743316]])

In [129]:
np.random.randint(10)  ###

<IPython.core.display.Javascript object>

9

In [137]:
np.random.randint(10,100,5)  ###

<IPython.core.display.Javascript object>

array([12, 28, 56, 99, 70])

In [142]:
a

array([[  1.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   1.]])

In [144]:
b=a
b

array([[  1.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   1.]])

In [145]:
import numpy as np
print(np.__version__)   ###uSING VERSION OF nUMPY

1.18.5


In [154]:
a

array([[  1.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   1.]])

In [158]:
a[1, 1:4]=[8,9,10]

In [159]:
a

array([[  1.,   0.,   0.,   0.],
       [  0.,   8.,   9.,  10.],
       [  0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   1.]])

In [160]:
a.T

array([[  1.,   0.,   0.,   0.],
       [  0.,   8.,   0.,   0.],
       [  0.,   9., 100.,   0.],
       [  0.,  10.,   0.,   1.]])

In [165]:
a=np.linspace(1,10,20)
a                             

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [166]:
a>3                 ##########Comparison

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [170]:
a=np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [171]:
a*100            ############Maths

array([ 100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,  900.,
       1000.])

In [172]:
a-20

array([-19., -18., -17., -16., -15., -14., -13., -12., -11., -10.])

In [173]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])